### PR TITLE
implementing #13

### PR DESCRIPTION
**Pull request by yury-dymov**

### CODE REVIEW

**Comment by SirLamer** [comment]
My version version checked for the exact object as you are (data type + id number), but what happens then is that the child relationship on every item includes a full copy list of all of the items from the parent list, except itself.

So, for example:

(store of elevators from one or a handful of buildings) -> building -> elevators

Each elevator will have a "building" reference which itself will have an "elevators" relationship from the API, which then points back at the entire collection of elevators. Each elevator will include within itself a full copy record of all elevators, except for itself.

**Comment by SirLamer** [comment]
By the way, I did have an idea about allowing an array of relationships to be eager loaded, using dot notion do denote child relationships, but settled on "just ignore it if the data type is the same" since those are very likely to be loaded in to the store as a separate lookup list in such a case.

**Comment by yury-dymov** [comment]
Well, you have a finite number of objects in the store and cache ensures that each object will be loaded only once — all copies are not actual copies but references.  So, eventually it will work fine. Regarding the extreme example, sounds more like a data model issue to me.

**Comment by SirLamer** [comment]
Yeah you're right, but in my example above, if you have 10 elevators and one building, and you eager loading the building with "elevators" relationship, and each elevator has a "building" relationship, and say you load the elevators from the store in to an array to be handled in the DOM to render a list, each elevator will have its own separate list of all of the other elevators from that building loaded within it. I used elevators and building as an example, but imagine a case with 100 or 1000 items bound to a common parents. That's a lot of memory dedicated to nothing useful.

**Comment by SirLamer** [comment]
I mean, I get this is why you used a loader function in the first place. ;-) But, I noticed that your package is very suitable to Vue and Vuex, and it relies on computed properties to clearly maintain separation of concerns and it doesn't work with the getter function.

**Comment by yury-dymov** [comment]
Well, I guess we need another approach for that but as for now I am not able to come up with a simple solution, which will work in general. 

Maybe we can have a callback function as an option, which will be called every time while we are building a relational objects to control if we need it or not

**Comment by SirLamer** [comment]
Yeah, well an array of relationships to eager load would work but that requires more micro-management. That's why I liked the "ignore if the same type" solution, it's simple and errs on the side of conserving memory. If another type of collection is needed in the DOM then use another computed property to generate it.

Or a hybrid - if eager loading is enabled, by default ignore relationships for the same data type as I implemented it, or if an array of dot-notation relationships is included, eager load those. I was trying to avoid bloating your nice little data store package too much, though.

**Comment by yury-dymov** [comment]
I see. I guess you can use your fork for some time before we come up to an elegant solution. 
I agree that "ignore if the same type" will work fine for you but it might create unobvious side-effects, which would take days to debug for others.

**Pull request merged**
