### PR TITLE
Multiple feature additions

### PR DESCRIPTION
**Pull request by SirLamer**
This PR adds the following.
- Optional retrieval of a collection of multiple items. If the 'id' parameter is a single value, behavior will remain identical to before. If the 'id' parameter is 'null' or omitted, all items for the given collection will be returned. If the 'id' parameter is an array of ID values, those will be returned.
- Optional eager loading of local resources. In this mode, relationship data is loaded immediately, instead of using the lazy loading getter. This is ideal for supporting computed properties in Vue.
- The "no remote lazy loading" error check can be suppressed. This is intended for use cases where it's desired to just ignore the 'links' JSON API property, usually for cases where the relationship data is not needed for a given case however the API by default provides the 'links' property on all requests.
- Added unit tests for the above.
- Some minor semantic changes to accommodate the above and maintain the small package size.

These should be non-breaking changes as the defaults of the new features are identical to the previous functionality.

Sorry for the bloated PR, I just kinda kept on going. ;-)

### CODE REVIEW

**Comment by yury-dymov** [comment]
Thank you for your work! Much appreciated! I will update the README and error message and publish it about one hour from now

**Comment by SirLamer** [comment]
Oh yeah, sorry I forgot about the readme. At least I wrote the tests, though. ;-)

**Comment by yury-dymov** [comment]
@SirLamer, no worries, you did a great job :) I've slightly changed interface of `build` function compared to your PR but I hope it wouldn't be a big issue for you

**Comment by SirLamer** [comment]
Nah I can make changes to suit, I only have three calls to it in a VueX getter interface. I am expecting to need to make changes to the store getters in the future and so am keeping them separate from the end-use code.

**Comment by SirLamer** [comment]
In the unit testing, I pulled in the Lodash method "isFunction" as a dependency but then later removed its use, so you could remove that one import line up top if you want. Otherwise, no harm there for the moment.

**Pull request merged**
