### PR TITLE
Support immutable.js redux state

### PR DESCRIPTION
**Pull request by lvauvillier**
And returns regular JS entities as expected :)
Tests are runs in both contexts.

### CODE REVIEW

**Comment by lvauvillier** [comment]
Hi @yury-dymov, I add `immutable` only as dev dependency (it is used only for testing).
The overhead of this PR is only several lines.

**Comment by yury-dymov** [comment]
@lvauvillier I am terribly sorry, you are correct. Don't see any reasons not to merge now.
Thank you!

**Comment by lvauvillier** [comment]
Thanks a lot for merging and your quick reply !

**Comment by yury-dymov** [comment]
:) Currently preparing to publish, will be live in ~10 minutes

**Pull request merged**
